version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5433:5432
    volumes:
      - ./datatest:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080